import Head from 'next/head';
import Image from 'next/image';
import AddPodcastForm from '../components/AddPodcastForm';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <>
      <Head>
        <title>Podcast App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div className='flex'>
        <section className='w-1/3 bg-green-600 h-screen p-8'>
          <div className='mb-3'>
            <h2 className='text-3xl text-white'>Add a Podcast</h2>
            <AddPodcastForm />
          </div>
        </section>
        <section className='w-2/3 h-screen p-8'>
          <div className='mb-3'>
            <h2 className='text-3xl text-green-600'>Podcasts</h2>
          </div>
        </section>
      </div>
    </>
  );
}
